name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Windows
      run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained true --runtime win-x64
    - name: Build Linux
      run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained true --runtime linux-x64
    - name: Build Mac
      run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained true --runtime osx-x64
